### ISSUE TITLE
[Feature request] Ability for members who wish to identify their Bitcoin addresses as signing keys only

### ISSUE THREAD

**Issue by ftrader** [BitcoinUnlimited/BitcoinUnlimitedWeb#119]
I would like to ask if it's possible to make the 'Bitcoin address' label display as 'BU signing address' when clicking on my name on the "members" page.

Reason:

As a member, I just use my Bitcoin address for signing, and I don't really want to encourage people to donate there. I would like to avoid the impression that my address might be simultaneously intended as a personal donation address.

I know this is an individual choice, and I don't want it to be enforced for others, but for my case I think it would help to avoid mistakes on the part of people who may wish to donate. I would prefer that they donate directly to BU's official donation address in that case.

The best solution would be to have 'BU signing address' be a hyperlink to some page (maybe in FAQ?) that explains how we use Bitcoin addresses for our electronic signatures when voting on BUIPs.

**Comment by sickpig** [comment]
agreed. someone else on reddit said I thought that the addresses were there to receive donations. 
(see https://www.reddit.com/r/btc/comments/68awst/new_bitcoin_unlimited_website_was_launched_today/dgx532c/)

I'm going to add a PR for that.

**Comment by sickpig** [comment]
see #121 

didn't add the link to a FAQ that explain how we use the addresses thou.

**Comment by sickpig** [comment]
@ftrader #121 merged and deployed. Do you think we could close this issue even if we don't have implemented the later part of your request (link to an explanation to a FAQ)?

**Comment by ftrader** [comment]
Verified, will close this. Any nice-to-have's like a link to "what are BU signing addresses?" can be implemented at some later time.

Thanks for the quick fix!
