### ISSUE TITLE
BUIP list on website out of sync with Github repo

### ISSUE THREAD

**Issue by ftrader** [BitcoinUnlimited/BitcoinUnlimitedWeb#130]
The list on the website at this page:

https://www.bitcoinunlimited.info/resources/buips

is out of sync, and I did not find a noticeable link from the voting section to the Github section.

It is problematic that we have this information (BUIPs) duplicated in so many places (forum, github, website, ...) which all need to be kept in sync.

The website list is also specifically wrong about BUIP051 - this one (CI) was renamed to BUIP052 and BUIP051 is now the CompactBlocks BUIP.

BUIPs 053 - 055 are missing on the site.

**Comment by sickpig** [comment]
I'll fix it later today. Thanks for noticing.

**Comment by sickpig** [comment]
closed by #131
