### ISSUE TITLE
Add BUIP submission and voting

### ISSUE THREAD

**Issue by thofmann** [BitcoinUnlimited/BitcoinUnlimitedWeb#14]
Members should be able to sign and submit BUIPs. They should also be able to sign and submit votes on these BUIPs. The server should automatically validate the signatures for BUIPs and votes.

**Comment by awemany** [comment]
Relevant progress on this front:

http://89.248.161.25/voting/
https://github.com/awemany/buvweb

**Comment by awemany** [comment]
Voting has its own repo now, at https://github.com/BitcoinUnlimited/BitcoinUnlimitedVotingWebService
This issue should be closed.

**Comment by sickpig** [comment]
closed by #125
