### ISSUE TITLE
Issue with numbering in AoF

### ISSUE THREAD

**Issue by Greg-Griffith** [BitcoinUnlimited/BitcoinUnlimitedWeb#209]
the numbering in section 2 goes from 2.4 to 2.6. It should be renumbered so that it is properly sequential.

**Comment by AndrewClifford** [comment]
I agree, and propose that we insert "2.5 Reserved for future use."
This retains the sense of existing historical references to 2.6 and greater.

**Comment by Greg-Griffith** [comment]
@solex It turns out after looking at the original document again, we do have a section 2.5. It just isnt easy to see because the spacing between it and 2.4 is messed up. 2.5 does not start on its own line. i fixed that in #213

**Comment by AndrewClifford** [comment]
Good to know and have this closed.
