### ISSUE TITLE
Revision to members list

### ISSUE THREAD

**Issue by AndrewClifford** [BitcoinUnlimited/BitcoinUnlimitedWeb#210]
This list is separate from the voting system list, so needs updating manually. 
https://bitcoinunlimited.info/about/members

digitsu has asked via PM to be removed.
also: Christoph Bergmann, adamstgbit, kostialevin are resigned or expired.

**Comment by sickpig** [comment]
will fix

**Comment by AndrewClifford** [comment]
Looks good to me. Thanks for the fast update.

**Comment by Greg-Griffith** [comment]
@AndrewClifford to clarify, does that mean digitsu resigned or just wanted to be removed from the list on the website?

**Comment by AndrewClifford** [comment]
He just wanted to be removed.

**Comment by Greg-Griffith** [comment]
IMO if you want to hide that you are in the org, you probably shouldn't be in it. I see this as the equivalent of having 1 foot out of the door.

**Comment by AndrewClifford** [comment]
Indeed. 
The middle-ground is to auto-generate the website list from the voting page, preserving bios and photos for those who have provided them. So, all members appear as names in the list, at a minimum.

**Comment by Greg-Griffith** [comment]
we can add that if you would like. I am unsure if that is a formal feature request or not

**Comment by sickpig** [comment]
ouch, I thought Jerry resigned rather the requested to be removed from the list while still remaining a member...

**Comment by sickpig** [comment]
going to put digitsu back until we settle this one.

**Comment by gandrewstone** [comment]
I think that we continue to list all members.  If the membership wants to allow hidden members, someone can make a BUIP and we can vote on that change.

You can be a member of a democratic organization and not agree with everything that's happening.  In a larger context, you can still own some coin, even though you don't agree with some of the political shenanigans or technical decisions.  

It is a real problem that the community is polarizing to the point where slight ideological differences create huge schisms, when our real fight is against the legacy financial system that seeks to rent-seek a minimum of 2.5% out of every transfer either via credit card payments or ATM fees, and implements a defacto tax on assets via a capital "gains" tax when no gain has happened -- instead the unit of value has been devalued through inflation.

SV or BTC aligned individuals CAN make a statement against this trend by remaining members of BU.  And they can encourage BU to engage in mutually beneficial research, even though the BU membership chose to not support SV of BTC in its full node software at this time.

**Comment by sickpig** [comment]
fixed by #211
