### ISSUE TITLE
BUIP list not up to date

### ISSUE THREAD

**Issue by soeren-b-c** [BitcoinUnlimited/BitcoinUnlimitedWeb#215]
The list of BUIPs (https://www.bitcoinunlimited.info/resources/buips) stops at 093 (and refers to the list here https://github.com/BitcoinUnlimited/BUIP which stops at 105).
Are the lists updated automatically. Is there a smart way to "export" the list from the forum / voting system, or should it be done 'by hand'?

I would be happy to do it, but don't feel like doing it manually, if someone already has a script that just needs to be run once.

**Comment by sickpig** [comment]
@soeren-b-c 

unfortunately we have no automatic way to update the list. Problem is that BUIPs are usually proposed and finalize via bitco.in/forum.

This means that those BUIPs have to be manually converted to a mediawiki format then added to BitcoinUnlimited/BUIP.

This is way the list is lagging far behind the actual list of BUIPs you could find here: https://bitco.in/forum/threads/buip-index.1414/

A possible solution to the issue at hands would be to have a way for members to propose BUIPs via bitcoinunlimited.info directly and then integrate such tools with the other part of the system, e.g. the voting sys.

**Comment by soeren-b-c** [comment]
Thanks @sickpig for your reply.

So adding them manually would be the way to go. Will look into that at some point then.

**Comment by soeren-b-c** [comment]
@sickpig Is there a reason for the use of mediawiki / html format, or could this be made in Markdown going forward?

**Comment by soeren-b-c** [comment]
@sickpig One more thing, is there a reason for the "non standard" ordering, or could/should that be changes as well.

Example from https://www.bitcoinunlimited.info/resources/buips:

BUIP090 – New Members For Election #9
 BUIP091 – NeWorkshop on Instant Transactions for Bitcoin
 BUIP092 – Move the official BU repository and issue tracker to GitLab
 **BUIP069** – Academic paper - Mining, Taxation and Public Goods in Bitcoin
 BUIP094 – BCH November upgrade - Re-enable Op Codes
 BUIP095 – BCH November upgrade - CHECKDATASIG & CHECKDATASIGVERIFY
 BUIP096 – BCH November upgrade - Enforced lexicographic transaction ordering
 BUIP097 – New Members For Election #10
 BUIP098 – Bitcoin Unlimited's Strategy for the November 2018 Hard Fork
 **BUIP093** – Specification - Graphene Relay

**Comment by sickpig** [comment]
> @sickpig Is there a reason for the use of mediawiki / html format, or could this be made in Markdown going forward?

markdown is ok

**Comment by sickpig** [comment]
> @sickpig One more thing, is there a reason for the "non standard" ordering, or could/should that be changes as well.

BUIP number assignment and order are handled by @AndrewClifford.

**Comment by sickpig** [comment]
fixed by #220
