### ISSUE TITLE
Add Donate page

### ISSUE THREAD

**Issue by jacksarrocco** [BitcoinUnlimited/BitcoinUnlimitedWeb#54]
I was looking for a page for donation on the website but it's not there. It would something very useful to maintain the project. Can we do it? I can help

**Comment by thofmann** [comment]
Thanks for opening the issue! I think that we do plan on adding a donation page. If you'd like to start working on one, it would be appreciated! Let me know if you start and need any help.

**Comment by jacksarrocco** [comment]
I've started working on it: https://github.com/jacksarrocco/BitcoinUnlimitedWeb/commit/0f34519f437306913766adcaa42a122bb5cd8c48. I created the new page, with new route, strings and a qr code image for the address. But I don't know where to have the link on the main menu, since it's already full.

**Comment by jacksarrocco** [comment]
#55
