### ISSUE TITLE
Add Official BU Ubuntu Repository in the download page

### ISSUE THREAD

**Issue by jacksarrocco** [BitcoinUnlimited/BitcoinUnlimitedWeb#57]
[s1ckpig](https://www.reddit.com/user/s1ckpig) recently wrote a [post](https://www.reddit.com/r/btc/comments/57rs49/official_bitcoin_unlimited_ubuntu_repository/) on Reddit about the Official BU Ubuntu Repository for PPA:

> This repo wil contain deb packages for BU stable release (as of this writing 0.12.1c).
> 
> Initially we are going to support 2 Ubuntu distros 14.04 LTS (trusty) and 16.04 LTS (xenial), 4 arch: i386, amd64, armhf, arm64.
> 
> This is the direct link:
> 
> https://launchpad.net/~bitcoin-unlimited/+archive/ubuntu/bu-ppa So to install the binaries for your ubuntu system:
> 
>     sudo apt-get install software-properties-common
>     sudo add-apt-repository ppa:bitcoin-unlimited/bu-ppa
>     sudo apt-get update
>     sudo apt-get install bitcoind bitcoin-qt
> 
> We are also providing a repository which will contains debs of the main development branch (0.12.1bu). Same distros and archs will be supported. You could find it here.

It'd be very useful to add them to the download page of the website

**Comment by sickpig** [comment]
I'll do it later tonight

**Comment by jacksarrocco** [comment]
Thanks, appreciated

**Comment by sickpig** [comment]
@jacksarrocco  this is done, if you want you could close the issue
