### ISSUE TITLE
npm run build deletes results of npm run bower

### ISSUE THREAD

**Issue by awemany** [BitcoinUnlimited/BitcoinUnlimitedWeb#98]
I do have another build system question/remark:

It looks like `npm run build` deletes the results of `npm run bower`. (Presumably in the clean step?)

Is there a way to keep the results or let `npm run build` remake them?

If that's not easily possible, for the node.js noobs like me, it would be great to put that into the documentation/README - that npm run build clears the results of `npm run bower`.

Thanks :)

**Comment by sickpig** [comment]
@awemany This problem should have been fixed since #117. if you have time could you please verify?

**Comment by sickpig** [comment]
@awemany fixed, we are not using bower anymore.
